version: 0.0
os: linux
files:
  - source: /src/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: src/install_dependencies
      timeout: 300
      runas: root
    - location: src/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: src/stop_server
      timeout: 300
      runas: root

